"""generate.py — Generate Terraform files from architecture infrastructure requirements.

Renders Jinja2 templates to produce .tf files for the target platform.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any


def _render_template(template_path: Path, context: dict[str, Any]) -> str:
    """Render a Jinja2 template. Falls back to simple string replace if jinja2 unavailable."""
    try:
        from jinja2 import Environment, FileSystemLoader

        env = Environment(
            loader=FileSystemLoader(str(template_path.parent)),
            keep_trailing_newline=True,
        )
        template = env.get_template(template_path.name)
        return template.render(**context)
    except ImportError:
        # Fallback: simple placeholder replacement
        text = template_path.read_text(encoding="utf-8")
        for key, value in context.items():
            text = text.replace(f"{{{{ {key} }}}}", str(value))
        return text


def generate_terraform(
    resources: list[dict[str, str]],
    platform: str,
    env: str,
    output_dir: Path,
) -> list[dict[str, Any]]:
    """Generate Terraform files from resource list.

    Returns list of action results compatible with provision.py log format.
    """
    templates_dir = Path(__file__).parent / "templates"
    template_file = templates_dir / f"{platform}.tf.j2"

    output_dir.mkdir(parents=True, exist_ok=True)
    results = []

    if not template_file.exists():
        results.append({
            "resource": {"platform": platform, "resource_type": "terraform", "name": "main.tf", "purpose": ""},
            "name": "main.tf",
            "action": "generate",
            "status": "error",
            "command": None,
            "output": f"Template not found: {template_file}",
        })
        return results

    # Render main.tf
    context = {
        "platform": platform,
        "env": env,
        "resources": resources,
    }
    content = _render_template(template_file, context)
    main_tf = output_dir / "main.tf"
    main_tf.write_text(content, encoding="utf-8")
    results.append({
        "resource": {"platform": platform, "resource_type": "terraform", "name": "main.tf", "purpose": ""},
        "name": "main.tf",
        "action": "generate",
        "status": "created",
        "command": None,
        "output": f"Generated: {main_tf}",
    })

    # Generate variables.tf
    variables_content = _generate_variables(resources, platform, env)
    variables_tf = output_dir / "variables.tf"
    variables_tf.write_text(variables_content, encoding="utf-8")
    results.append({
        "resource": {"platform": platform, "resource_type": "terraform", "name": "variables.tf", "purpose": ""},
        "name": "variables.tf",
        "action": "generate",
        "status": "created",
        "command": None,
        "output": f"Generated: {variables_tf}",
    })

    return results


def _generate_variables(
    resources: list[dict[str, str]], platform: str, env: str
) -> str:
    """Generate variables.tf content."""
    lines = [
        '# Auto-generated by datacoolie-provision',
        f'# Platform: {platform}, Environment: {env}',
        '',
        'variable "environment" {',
        '  description = "Deployment environment"',
        '  type        = string',
        f'  default     = "{env}"',
        '}',
        '',
    ]

    if platform == "aws":
        lines.extend([
            'variable "aws_region" {',
            '  description = "AWS region"',
            '  type        = string',
            '  default     = "us-east-1"',
            '}',
            '',
        ])
    elif platform == "databricks":
        lines.extend([
            'variable "databricks_host" {',
            '  description = "Databricks workspace URL"',
            '  type        = string',
            '}',
            '',
            'variable "databricks_token" {',
            '  description = "Databricks access token"',
            '  type        = string',
            '  sensitive   = true',
            '}',
            '',
        ])
    elif platform == "fabric":
        lines.extend([
            'variable "workspace_id" {',
            '  description = "Fabric workspace ID"',
            '  type        = string',
            '}',
            '',
        ])

    return "\n".join(lines)
