#!/usr/bin/env python3
"""Verify an immutable build and an optional explicit verification receipt."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import datetime
from pathlib import Path, PurePosixPath
from typing import Any
from urllib.parse import urlparse

from jsonschema import Draft202012Validator, FormatChecker

from materialize import resolve_current_build, verify_build


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _load_object(path: Path, label: str) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"{label} is not valid JSON: {path}") from exc
    if not isinstance(payload, dict):
        raise ValueError(f"{label} must contain an object: {path}")
    return payload


def _validate_receipt_schema(receipt: dict[str, Any]) -> None:
    schema_path = (
        Path(__file__).resolve().parent.parent
        / "schemas"
        / "build-verification-receipt.schema.json"
    )
    schema = _load_object(schema_path, "Build verification schema")
    validator = Draft202012Validator(schema, format_checker=FormatChecker())
    errors = sorted(
        validator.iter_errors(receipt),
        key=lambda error: tuple(str(part) for part in error.absolute_path),
    )
    if errors:
        details = []
        for error in errors:
            location = ".".join(str(part) for part in error.absolute_path) or "<root>"
            details.append(f"{location}: {error.message}")
        raise ValueError("Invalid build verification receipt:\n- " + "\n- ".join(details))


def _artifact_map(manifest: dict[str, Any]) -> dict[str, str]:
    artifacts = manifest.get("artifacts")
    if not isinstance(artifacts, list):
        raise ValueError("Build manifest artifacts must be an array")
    result: dict[str, str] = {}
    for item in artifacts:
        if not isinstance(item, dict) or not isinstance(item.get("path"), str):
            raise ValueError("Build manifest contains an invalid artifact entry")
        path = item["path"]
        digest = item.get("sha256")
        if path in result:
            raise ValueError(f"Build manifest contains duplicate artifact path: {path}")
        if not isinstance(digest, str):
            raise ValueError(f"Build manifest artifact has no SHA-256: {path}")
        result[path] = digest
    return result


def _require_artifact(
    build_dir: Path,
    artifacts: dict[str, str],
    receipt_artifact: dict[str, str],
    expected_path: str,
) -> None:
    actual_path = receipt_artifact["path"]
    if actual_path != expected_path:
        raise ValueError(f"Receipt artifact path mismatch: expected {expected_path}, got {actual_path}")
    if actual_path not in artifacts:
        raise ValueError(f"Receipt artifact is not declared by the build manifest: {actual_path}")
    expected_digest = artifacts[actual_path]
    if receipt_artifact["sha256"] != expected_digest:
        raise ValueError(f"Receipt artifact hash mismatch: {actual_path}")
    artifact_path = build_dir / PurePosixPath(actual_path)
    try:
        artifact_path.resolve().relative_to(build_dir)
    except ValueError as exc:
        raise ValueError(f"Receipt artifact escapes the build directory: {actual_path}") from exc
    if not artifact_path.is_file() or _sha256(artifact_path) != expected_digest:
        raise ValueError(f"Receipt artifact does not match generated bytes: {actual_path}")


def _require_persistent_path(value: str, label: str) -> None:
    path_parts = PurePosixPath(urlparse(value).path.replace("\\", "/")).parts
    if ".builds" in {part.lower() for part in path_parts}:
        raise ValueError(f"Receipt {label} must remain outside .builds/")


def validate_receipt(
    build_dir: Path,
    receipt_path: Path,
    *,
    require_success: bool = False,
) -> dict[str, Any]:
    """Validate one explicitly selected receipt against exact generated artifacts."""
    if receipt_path.is_symlink():
        raise ValueError(f"Build verification receipt must not be a symlink: {receipt_path}")
    build_dir = build_dir.resolve()
    manifest = verify_build(build_dir)
    receipt = _load_object(receipt_path, "Build verification receipt")
    _validate_receipt_schema(receipt)

    if receipt_path.stem != receipt["receipt_id"]:
        raise ValueError("Receipt filename must match receipt_id")
    artifacts_dir = build_dir.parent
    builds_dir = artifacts_dir.parent
    if artifacts_dir.name != "artifacts" or builds_dir.name != ".builds":
        raise ValueError("Build must be stored under .builds/artifacts/{build_id}")
    expected_parent = (
        builds_dir
        / "evidence"
        / build_dir.name
        / receipt["environment"]
    ).resolve()
    if receipt_path.resolve().parent != expected_parent:
        raise ValueError(f"Receipt must be stored under {expected_parent}")
    if receipt["build_id"] != manifest.get("build_id"):
        raise ValueError("Receipt build_id does not match the build manifest")
    environments = manifest.get("environments")
    if not isinstance(environments, dict) or receipt["environment"] not in environments:
        raise ValueError("Receipt environment is not declared by the build manifest")
    environment = environments[receipt["environment"]]
    if receipt["platform"] != environment.get("platform"):
        raise ValueError("Receipt platform does not match the build environment")
    if receipt["datacoolie_version"] != manifest.get("datacoolie_version"):
        raise ValueError("Receipt DataCoolie version does not match the build manifest")

    artifacts = _artifact_map(manifest)
    runners = environment.get("runners")
    if not isinstance(runners, list) or receipt["runner"]["path"] not in runners:
        raise ValueError("Receipt runner is not declared for the build environment")
    _require_artifact(
        build_dir,
        artifacts,
        receipt["runner"],
        receipt["runner"]["path"],
    )
    _require_artifact(
        build_dir,
        artifacts,
        receipt["metadata"],
        str(environment.get("metadata")),
    )

    expected_functions = manifest.get("functions") or []
    actual_function_paths = [item["path"] for item in receipt["functions"]]
    if len(actual_function_paths) != len(set(actual_function_paths)):
        raise ValueError("Receipt contains duplicate functions artifacts")
    if set(actual_function_paths) != set(expected_functions):
        raise ValueError("Receipt functions do not match the build manifest")
    for item in receipt["functions"]:
        _require_artifact(build_dir, artifacts, item, item["path"])

    runner_name = PurePosixPath(receipt["runner"]["path"]).name
    if not runner_name.startswith(f"{receipt['operation']}_"):
        raise ValueError("Receipt operation does not match the selected runner")
    _require_persistent_path(receipt["base_log_path"], "base_log_path")
    _require_persistent_path(receipt["watermark_base_path"], "watermark_base_path")

    started = datetime.fromisoformat(receipt["started_at"].replace("Z", "+00:00"))
    finished = datetime.fromisoformat(receipt["finished_at"].replace("Z", "+00:00"))
    if started.tzinfo is None or finished.tzinfo is None:
        raise ValueError("Receipt timestamps require timezones")
    if finished < started:
        raise ValueError("Receipt finished_at must not precede started_at")
    if receipt["status"] == "succeeded" and not any(
        check["name"] == "generated-runtime-execution" and check["status"] == "passed"
        for check in receipt["checks"]
    ):
        raise ValueError(
            "A successful receipt requires a passed generated-runtime-execution check"
        )
    if require_success and receipt["status"] != "succeeded":
        raise ValueError("A successful build verification receipt is required")
    return receipt


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    selector = parser.add_mutually_exclusive_group(required=True)
    selector.add_argument("--build-dir", type=Path)
    selector.add_argument(
        "--current",
        metavar="ENV",
        help="Resolve .builds/current/<env>.json before validation",
    )
    parser.add_argument("--workspace", type=Path)
    parser.add_argument("--receipt", type=Path, help="Explicit receipt path; never inferred")
    parser.add_argument("--require-success", action="store_true")
    args = parser.parse_args()
    if args.current and args.workspace is None:
        parser.error("--current requires --workspace")
    if args.build_dir and args.workspace is not None:
        parser.error("--workspace is used only with --current")
    if args.require_success and args.receipt is None:
        parser.error("--require-success requires --receipt")
    try:
        build_dir = (
            resolve_current_build(args.workspace, args.current)
            if args.current
            else args.build_dir
        )
        manifest = verify_build(build_dir)
        if args.receipt:
            receipt = validate_receipt(
                build_dir,
                args.receipt,
                require_success=args.require_success,
            )
            print(f"OK: verified receipt {receipt['receipt_id']} for build {manifest['build_id']}")
        else:
            print(f"OK: verified build {manifest['build_id']}")
    except (OSError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
