"""Template content for generated project files.

Kept here as string constants to avoid Jinja2 dependency for the skill.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# .datacoolie/config.yaml
# ---------------------------------------------------------------------------

CONFIG_YAML = """\
# DataCoolie project configuration
# Generated by datacoolie-init scaffold

project_name: "{project_name}"

engine_strategy:
  # Options: polars, spark, mixed
  default: "{default_engine}"
{engine_overrides}
platforms:
{platforms_yaml}
medallion_layers:
{layers_yaml}
"""

# ---------------------------------------------------------------------------
# metadata/connections.json
# ---------------------------------------------------------------------------

CONNECTIONS_JSON_FILE = """\
[
  {{
    "name": "{source_conn_name}",
    "connection_type": "file",
    "format": "{source_format}",
    "configure": {{
      "base_path": "./data/eval/input/{source_format}"
    }}
  }},
  {{
    "name": "{dest_conn_name}",
    "connection_type": "{dest_connection_type}",
    "format": "{dest_format}",
    "configure": {{
      "base_path": "./data/eval/output/{dest_format}"
    }}
  }}
]
"""

CONNECTIONS_JSON_DB = """\
[
  {{
    "name": "{source_conn_name}",
    "connection_type": "database",
    "format": "sql",
    "configure": {{
      "host": "localhost",
      "port": 5432,
      "database": "{project_name}",
      "database_type": "postgresql"
    }}
  }},
  {{
    "name": "{dest_conn_name}",
    "connection_type": "{dest_connection_type}",
    "format": "{dest_format}",
    "configure": {{
      "base_path": "./data/eval/output/{dest_format}"
    }}
  }}
]
"""

CONNECTIONS_JSON_API = """\
[
  {{
    "name": "{source_conn_name}",
    "connection_type": "api",
    "format": "api",
    "configure": {{
      "url": "https://api.example.com",
      "endpoint": "/data"
    }}
  }},
  {{
    "name": "{dest_conn_name}",
    "connection_type": "{dest_connection_type}",
    "format": "{dest_format}",
    "configure": {{
      "base_path": "./data/eval/output/{dest_format}"
    }}
  }}
]
"""

# ---------------------------------------------------------------------------
# metadata/dataflows.json
# ---------------------------------------------------------------------------

DATAFLOWS_JSON = """\
[
  {{
    "name": "{dataflow_name}",
    "stage": "{stage}",
    "source": {{
      "connection_name": "{source_conn_name}",
      "table": "sample_table"
    }},
    "destination": {{
      "connection_name": "{dest_conn_name}",
      "table": "sample_table",
      "load_type": "full_load"
    }}
  }}
]
"""

# ---------------------------------------------------------------------------
# metadata/environments/dev.yaml
# ---------------------------------------------------------------------------

ENV_DEV_YAML = """\
# Environment overlay for dev
# Override connection paths, credentials, etc.
connections:
  - name: "{dest_conn_name}"
    configure:
      base_path: "./data/eval/output/{dest_format}"
"""

ENV_PROD_YAML = """\
# Environment overlay for prod
# Override connection paths for production storage
connections:
  - name: "{dest_conn_name}"
    configure:
      base_path: "/prod/output/{dest_format}"
"""

# ---------------------------------------------------------------------------
# scripts/run_local.py
# ---------------------------------------------------------------------------

RUN_LOCAL_PY = """\
\"\"\"Local runner script — execute DataCoolie pipelines locally.

Usage:
    python scripts/run_local.py [--stage STAGE] [--dry-run]
    python scripts/run_local.py --stage source2bronze
    python scripts/run_local.py --stage source2bronze,bronze2silver --engine spark
\"\"\"
from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

# Add project root to path so that functions.* modules are importable.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from datacoolie.core import DataCoolieRunConfig
from datacoolie.engines import PolarsEngine
from datacoolie.metadata import FileProvider
from datacoolie.orchestration import DataCoolieDriver
from datacoolie.platforms import LocalPlatform

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("run_local")

_METADATA_PATH = str(Path(__file__).resolve().parent.parent / "metadata" / "metadata.json")


def main():
    parser = argparse.ArgumentParser(description="DataCoolie local runner")
    parser.add_argument("--stage", default="", help="Stage filter (empty = all stages)")
    parser.add_argument("--engine", default="{default_engine}", choices=["polars", "spark"],
                        help="Execution engine")
    parser.add_argument("--dry-run", action="store_true", help="Log planned work without writing")
    args = parser.parse_args()

    platform = LocalPlatform()

    if args.engine == "spark":
        from pyspark.sql import SparkSession
        from datacoolie.engines import SparkEngine
        spark = SparkSession.builder.appName("{project_name}").getOrCreate()
        engine = SparkEngine(spark_session=spark, platform=platform)
    else:
        engine = PolarsEngine(platform=platform)

    metadata = FileProvider(config_path=_METADATA_PATH, platform=platform)
    config = DataCoolieRunConfig(dry_run=args.dry_run)

    with DataCoolieDriver(
        engine=engine,
        platform=platform,
        metadata_provider=metadata,
        config=config,
    ) as driver:
        if args.dry_run:
            dataflows = driver.load_dataflows(stage=args.stage or None)
            logger.info("Dry run — %d dataflow(s) matched:", len(dataflows))
            for df in dataflows:
                logger.info("  - [%s] %s", df.stage or "-", df.name)
            return

        result = driver.run(stage=args.stage or None, column_name_mode="lower")
        logger.info(
            "Done — total: %d, succeeded: %d, failed: %d, skipped: %d (%.1fs)",
            result.total, result.succeeded, result.failed, result.skipped,
            result.duration_seconds,
        )
        if result.has_failures:
            sys.exit(2)


if __name__ == "__main__":
    main()
"""

# ---------------------------------------------------------------------------
# scripts/run_local.py (split layout — connections_path overlay)
# ---------------------------------------------------------------------------

RUN_LOCAL_PY_SPLIT = """\
\"\"\"Local runner script — execute DataCoolie pipelines locally.

Usage:
    python scripts/run_local.py [--stage STAGE] [--dry-run]
    python scripts/run_local.py --stage source2bronze
    python scripts/run_local.py --stage source2bronze,bronze2silver --engine spark
\"\"\"
from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

# Add project root to path so that functions.* modules are importable.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from datacoolie.core import DataCoolieRunConfig
from datacoolie.engines import PolarsEngine
from datacoolie.metadata import FileProvider
from datacoolie.orchestration import DataCoolieDriver
from datacoolie.platforms import LocalPlatform

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("run_local")

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
_DATAFLOWS_PATH = str(_PROJECT_ROOT / "metadata" / "dataflows.json")
_CONNECTIONS_PATH = str(_PROJECT_ROOT / "metadata" / "connections.json")


def main():
    parser = argparse.ArgumentParser(description="DataCoolie local runner")
    parser.add_argument("--stage", default="", help="Stage filter (empty = all stages)")
    parser.add_argument("--engine", default="{default_engine}", choices=["polars", "spark"],
                        help="Execution engine")
    parser.add_argument("--dry-run", action="store_true", help="Log planned work without writing")
    args = parser.parse_args()

    platform = LocalPlatform()

    if args.engine == "spark":
        from pyspark.sql import SparkSession
        from datacoolie.engines import SparkEngine
        spark = SparkSession.builder.appName("{project_name}").getOrCreate()
        engine = SparkEngine(spark_session=spark, platform=platform)
    else:
        engine = PolarsEngine(platform=platform)

    metadata = FileProvider(
        config_path=_DATAFLOWS_PATH,
        connections_path=_CONNECTIONS_PATH,
        platform=platform,
    )
    config = DataCoolieRunConfig(dry_run=args.dry_run)

    with DataCoolieDriver(
        engine=engine,
        platform=platform,
        metadata_provider=metadata,
        config=config,
    ) as driver:
        if args.dry_run:
            dataflows = driver.load_dataflows(stage=args.stage or None)
            logger.info("Dry run — %d dataflow(s) matched:", len(dataflows))
            for df in dataflows:
                logger.info("  - [%s] %s", df.stage or "-", df.name)
            return

        result = driver.run(stage=args.stage or None, column_name_mode="lower")
        logger.info(
            "Done — total: %d, succeeded: %d, failed: %d, skipped: %d (%.1fs)",
            result.total, result.succeeded, result.failed, result.skipped,
            result.duration_seconds,
        )
        if result.has_failures:
            sys.exit(2)


if __name__ == "__main__":
    main()
"""

# ---------------------------------------------------------------------------
# functions/__init__.py and functions/sources.py
# ---------------------------------------------------------------------------

FUNCTIONS_INIT_PY = """\
\"\"\"Custom source/transform functions for {project_name}.\"\"\"
"""

FUNCTIONS_SOURCES_PY = """\
\"\"\"Custom source functions.

The framework calls functions with keyword arguments:
    engine          -- active BaseEngine instance (PolarsEngine or SparkEngine)
    source          -- Source model for this dataflow
    watermark_start -- previous watermark dict (None on first run)
    watermark_end   -- replay ceiling watermark (None for normal incremental reads)

Use *args, **kwargs so functions don't break when new kwargs are added
and to allow simple functions that ignore watermarks entirely.

Reference in metadata via source.python_function:
    "functions.sources.my_custom_source"
\"\"\"
from __future__ import annotations


def sample_source(*args, **kwargs):
    \"\"\"Example custom source — replace with your logic.\"\"\"
    engine          = kwargs.get("engine")
    source          = kwargs.get("source")
    watermark_start = kwargs.get("watermark_start")  # None on first run
    watermark_end   = kwargs.get("watermark_end")    # None unless replaying
    # Use engine.execute_sql() or engine.create_dataframe() here.
    return None
"""

FUNCTIONS_PYPROJECT_TOML = """\
[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{project_name}-functions"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
"""

# ---------------------------------------------------------------------------
# .gitignore
# ---------------------------------------------------------------------------

GITIGNORE = """\
# DataCoolie generated
.datacoolie/generated/
data/eval/output/
*.pyc
__pycache__/
.venv/
*.egg-info/
dist/
build/

# IDE
.vscode/
.idea/

# OS
.DS_Store
Thumbs.db
"""

# ---------------------------------------------------------------------------
# requirements.txt
# ---------------------------------------------------------------------------

REQUIREMENTS_TXT = """\
datacoolie>=0.1.0
"""
