"""ProperDocs hook: supply useful metadata for virtual blog listing pages."""

from __future__ import annotations


def on_page_context(context, page, config, nav):  # noqa: ANN001
    """Set descriptions for blog pages generated by the Material blog plugin."""
    if page.url.startswith("blog/category/"):
        page.meta["description"] = (
            f"Browse DataCoolie's {page.title} articles for practical Python ETL "
            "guidance, Spark and Polars examples, lakehouse patterns, and "
            "framework decisions."
        )
    elif page.url.startswith("blog/archive/"):
        page.meta["description"] = (
            f"Browse DataCoolie's {page.title} data engineering articles covering "
            "Python ETL, Spark, Polars, lakehouse patterns, and framework comparisons."
        )

    return context
