name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  github-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          generate_release_notes: true
          make_latest: true